flowchart TD
    Trigger[Google Drive Trigger] --> ListaMovimentacoesNovas[Lista Movimentações Novas]
    ListaMovimentacoesNovas --> DownloadFile[Download file]
    DownloadFile --> GetMovimentacao[get movimentação]
    GetMovimentacao --> GetMovimentacaoNovas[get movimentação novas]
    GetMovimentacao --> GetRendaPassivaNovas[get Renda Passiva novas]
    GetMovimentacaoNovas --> OrdenaCronologicamente[Ordena cronologicamente]
    OrdenaCronologicamente --> AdicionaMovimentacoes[adiciona na Movimentações]
    AdicionaMovimentacoes --> ArquivaMovimentacoes[Arquiva Movimentações]
    GetRendaPassivaNovas --> FiltraRecebimentos[filtra recebimentos]
    FiltraRecebimentos --> OrdenaCronologicamente1[Ordena cronologicamente1]
    OrdenaCronologicamente1 --> AdicionaRendaPassiva[adiciona na Renda Passiva]
