flowchart LR
  N0["CONFIG"]
  N1["Convert to File"]
  N2["HasFile?"]
  N3["Extract from File"]
  N4["Main Page"]
  N5["Instance overview"]
  N6["Sort-workflows"]
  N7["doc action"]
  N8["Empty Set"]
  N9["Load Doc File"]
  N10["Respond with markdown"]
  N11["Respond with HTML"]
  N12["Save New Doc File"]
  N13["Blank Doc File"]
  N14["Fetch Single Workflow1"]
  N15["Fill Workflow Table"]
  N16["Basic LLM Chain"]
  N17["OpenAI Chat Model"]
  N18["Structured Output Parser"]
  N19["Auto-fixing Output Parser"]
  N20["Respond with main page HTML"]
  N21["Workflow Tags"]
  N22["Fallback file name"]
  N23["mkdir"]
  N24["Merge1"]
  N25["Edit Page"]
  N26["Workflow md content"]
  N27["Is Action Edit?1"]
  N28["Is Action Edit?2"]
  N29["Generate Mermaid Chart"]
  N30["Merge2"]
  N31["Generated Doc"]
  N32["Passthrough"]
  N33["Merge3"]
  N34["Merge4"]
  N35["Merge5"]
  N36["Edit Fields"]
  N37["Is Action Save?"]
  N38["Merge6"]
  N39["Respond OK on Save"]
  N40["single workflow"]
  N41["file types"]
  N42["Get All Workflows"]
  N43["md files"]
  N44["Get Workflow tags"]
  N45["Sticky Note9"]
  N46["Sticky Note11"]
  N47["docsify"]
  N48["No Operation, do nothing1"]
  N49["Merge7"]
  N50["Sticky Note12"]
  N51["Sticky Note13"]
  N52["Sticky Note14"]
  N53["Sticky Note15"]
  N54["Sticky Note16"]
  N55["Sticky Note17"]
  N56["Sticky Note18"]
  N57["Sticky Note19"]
  N58["Sticky Note20"]
  N59["Sticky Note21"]
  N0 --> N34
  N0 --> N35
  N24 --> N2
  N30 --> N31
  N33 --> N28
  N34 --> N4
  N35 --> N41
  N38 --> N37
  N47 --> N0
  N47 --> N34
  N2 --> N3
  N2 --> N14
  N43 --> N42
  N43 --> N7
  N43 --> N44
  N43 --> N48
  N25 --> N11
  N8 --> N24
  N4 --> N20
  N7 --> N9
  N7 --> N32
  N7 --> N8
  N7 --> N36
  N41 --> N43
  N36 --> N1
  N36 --> N38
  N32 --> N33
  N32 --> N49
  N31 --> N1
  N31 --> N28
  N9 --> N24
  N21 --> N10
  N13 --> N28
  N6 --> N15
  N16 --> N30
  N1 --> N12
  N37 --> N39
  N40 --> N0
  N40 --> N35
  N27 --> N13
  N27 --> N16
  N27 --> N30
  N28 --> N25
  N28 --> N26
  N3 --> N33
  N42 --> N6
  N44 --> N21
  N5 --> N10
  N12 --> N38
  N22 --> N10
  N15 --> N5
  N26 --> N10
  N14 --> N29
  N14 --> N49
  N29 --> N49
  N48 --> N22
  N49 --> N27